name: Manual Deploy to Azure VM

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag version to deploy'
        required: true
        default: 'v1.0.0'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH 
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.71.16.154 >> ~/.ssh/known_hosts

      - name: Connect to VM and deploy tag
        run: |
          TAG_NAME="${{ github.event.inputs.tag }}"

          ssh -i ~/.ssh/id_rsa testadmin@13.71.16.154 << EOF
            echo 'Connected to Azure VM'
            
            # Update and install necessary packages
            sudo apt-get update
            sudo apt-get install -y docker.io docker-compose

            # Create a directory for the repo
            mkdir -p ~/repo2
            cd ~/repo2

            # Clone the repository if not already cloned
            if [ ! -d ".git" ]; then
              git clone https://github.com/BENZ199/manual-deploy-repo.git .
            else
              echo 'Repository already cloned'

              git pull
            fi

            # Checkout the specified tag
            git fetch --tags
            git checkout $TAG_NAME

            
            
            
          EOF

